import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Build a self-contained page that can be opened directly with file://.
// The checked-in application files stay unchanged; no package install is needed.
const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
const [page, styles] = await Promise.all([
  readFile(path.join(repositoryRoot, 'index.html'), 'utf8'),
  readFile(path.join(repositoryRoot, 'src/styles.css'), 'utf8'),
]);

function replaceExactlyOnce(source, pattern, replacement, label) {
  const matches = source.match(pattern);
  if (!matches || matches.length !== 1) {
    throw new Error(`Expected exactly one ${label}; review the offline builder after application changes.`);
  }
  return source.replace(pattern, () => replacement);
}

// These local modules use named imports and named declarations only. Keep each
// one in its own scope so shared helper names cannot collide in the HTML file.
const allowedModules = new Set(['app.js', 'analysis.js', 'section.js', 'chart.js']);
const completed = new Set();
const visiting = new Set();
const compiledModules = [];
async function compileModule(name) {
  if (!allowedModules.has(name)) throw new Error(`Unsupported offline dependency: ${name}`);
  if (completed.has(name)) return;
  if (visiting.has(name)) throw new Error(`Circular offline dependency: ${name}`);
  visiting.add(name);
  let source = await readFile(path.join(repositoryRoot, 'src', name), 'utf8');
  const importPattern = /^[ \t]*import\s+\{([^}]+)\}\s+from\s+['"]\.\/([\w-]+\.js)['"];?[ \t]*(?:\r?\n|$)/gm;
  const imports = [...source.matchAll(importPattern)];
  for (const match of imports) await compileModule(match[2]);
  source = source.replace(importPattern, (_, names, dependency) => {
    const bindings = names.trim().split(',').filter((item) => item.trim()).map((item) => {
      const match = item.trim().match(/^([A-Za-z_$][\w$]*)(?:\s+as\s+([A-Za-z_$][\w$]*))?$/);
      if (!match) throw new Error(`Unsupported named import in ${name}: ${item}`);
      return match[2] ? `${match[1]}: ${match[2]}` : match[1];
    });
    return `const { ${bindings.join(', ')} } = __modules[${JSON.stringify(dependency)}];\n`;
  });
  const exports = [...source.matchAll(/^[ \t]*export\s+(?:(?:async\s+)?function|class|const|let)\s+([A-Za-z_$][\w$]*)/gm)].map((match) => match[1]);
  source = source.replace(/^[ \t]*export\s+(?=(?:async\s+)?function\b|class\b|const\b|let\b)/gm, '');
  if (/^[ \t]*(?:import|export)\s/m.test(source)) {
    throw new Error(`Unsupported module declaration in ${name}`);
  }
  compiledModules.push(`__modules[${JSON.stringify(name)}] = (() => {\n${source}\nreturn { ${exports.join(', ')} };\n})();`);
  visiting.delete(name);
  completed.add(name);
}
await compileModule('app.js');
const bundledScript = `'use strict';\n(() => {\nconst __modules = Object.create(null);\n${compiledModules.join('\n')}\n})();`;
if (/<\/style\b/i.test(styles)) {
  throw new Error('Unexpected HTML style terminator in CSS.');
}
if (/\b(?:@import|url\s*\()/i.test(styles)) {
  throw new Error('The stylesheet contains a dependency; review it before building an offline page.');
}

let output = replaceExactlyOnce(
  page,
  /<link\s+rel="stylesheet"\s+href="\/src\/styles\.css"\s*\/?>/g,
  `<style>\n${styles}\n    </style>`,
  'stylesheet link',
);
output = replaceExactlyOnce(
  output,
  /^[ \t]*<script\s+type="module"\s+src="\/src\/app\.js"><\/script>[ \t]*(?:\r?\n|$)/gm,
  '',
  'module script',
);
output = replaceExactlyOnce(
  output,
  /<\/body>/g,
  `    <script>\n${bundledScript.replace(/<\/script/gi, '<\\/script')}\n    </script>\n  </body>`,
  'body terminator',
);
output = output.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by node scripts/build-offline.mjs. Self-contained; no server or network required. -->');

if (/<(?:script|link)\b[^>]*(?:src|href)\s*=/i.test(output)) {
  throw new Error('An external script or stylesheet remains in the offline output.');
}

const outputPath = path.join(repositoryRoot, 'pilar-offline.html');
await writeFile(outputPath, output, 'utf8');
console.log(`Created ${outputPath} (${Buffer.byteLength(output, 'utf8')} bytes).`);
