import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Build a self-contained page that can be opened directly with file://.
// The checked-in application files stay unchanged; no package install is needed.
const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
const [page, styles, engine, application] = await Promise.all([
  readFile(path.join(repositoryRoot, 'index.html'), 'utf8'),
  readFile(path.join(repositoryRoot, 'src/styles.css'), 'utf8'),
  readFile(path.join(repositoryRoot, 'src/analysis.js'), 'utf8'),
  readFile(path.join(repositoryRoot, 'src/app.js'), 'utf8'),
]);

function replaceExactlyOnce(source, pattern, replacement, label) {
  const matches = source.match(pattern);
  if (!matches || matches.length !== 1) {
    throw new Error(`Expected exactly one ${label}; review the offline builder after application changes.`);
  }
  return source.replace(pattern, () => replacement);
}

const classicEngine = engine.replace(/^export\s+(?=class\s+InputValidationError\b|function\s+analyzeColumn\b)/gm, '');
const classicApplication = replaceExactlyOnce(
  application,
  /^import\s+\{\s*analyzeColumn,\s*InputValidationError\s*\}\s+from\s+['"]\.\/analysis\.js['"];?\s*$/gm,
  '',
  'analysis import',
);
const bundledScript = `'use strict';\n(() => {\n${classicEngine}\n${classicApplication}\n})();`;

if (/^\s*(?:import|export)\s/m.test(bundledScript)) {
  throw new Error('An unsupported module declaration remains in the offline script.');
}
if (/<\/style\b/i.test(styles)) {
  throw new Error('Unexpected HTML style terminator in CSS.');
}
if (/\b(?:@import|url\s*\()/i.test(styles)) {
  throw new Error('The stylesheet contains a dependency; review it before building an offline page.');
}

let output = replaceExactlyOnce(
  page,
  /<link\s+rel="stylesheet"\s+href="\/src\/styles\.css"\s*\/?>/g,
  `<style>\n${styles}\n    </style>`,
  'stylesheet link',
);
output = replaceExactlyOnce(
  output,
  /^[ \t]*<script\s+type="module"\s+src="\/src\/app\.js"><\/script>[ \t]*(?:\r?\n|$)/gm,
  '',
  'module script',
);
output = replaceExactlyOnce(
  output,
  /<\/body>/g,
  `    <script>\n${bundledScript.replace(/<\/script/gi, '<\\/script')}\n    </script>\n  </body>`,
  'body terminator',
);
output = output.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by node scripts/build-offline.mjs. Self-contained; no server or network required. -->');

if (/<(?:script|link)\b[^>]*(?:src|href)\s*=/i.test(output)) {
  throw new Error('An external script or stylesheet remains in the offline output.');
}

const outputPath = path.join(repositoryRoot, 'pilar-offline.html');
await writeFile(outputPath, output, 'utf8');
console.log(`Created ${outputPath} (${Buffer.byteLength(output, 'utf8')} bytes).`);
